name: multicamera
description: Multiplexed cameras
version: 1.0.0
homepage: https://github.com/alexdempster44/multicamera

environment:
  flutter: ">=3.35.0"
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: my.alexl.multicamera
        pluginClass: MulticameraPlugin
      ios:
        pluginClass: MulticameraPlugin
