name: multicamera
description: A Flutter plugin for managing multiple camera instances simultaneously with built-in ML kit support.
version: 1.2.1
homepage: https://github.com/alexdempster44/multicamera

environment:
  flutter: ">=3.35.0"
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: my.alexl.multicamera
        pluginClass: MulticameraPlugin
      ios:
        pluginClass: MulticameraPlugin
